language: python
python: 2.7
sudo: required
branches:
  only:
    - master

before_install:
  - pip install python-openstackclient python-glanceclient
  - sudo apt-get install software-properties-common -y && sudo apt-add-repository ppa:ansible/ansible -y && sudo apt-get update
  - sudo apt-get install -y unzip ansible && wget https://releases.hashicorp.com/packer/0.12.2/packer_0.12.2_linux_amd64.zip && unzip packer_0.12.2_linux_amd64.zip
  - sudo mv packer /usr/bin/packer && chmod +x /usr/bin/packer

script:
  - ansible-playbook build.playbook.yml -e build-vars.yml

