language: python
python: 2.7
sudo: required
branches:
  only:
    - master

before_install:
  - pip install python-openstackclient python-glanceclient ansible pyopenssl ndg-httpsclient pyasn1 os-client-config
  - sudo apt-get install -y unzip ansible && wget https://releases.hashicorp.com/packer/0.12.2/packer_0.12.2_linux_amd64.zip && unzip packer_0.12.2_linux_amd64.zip
  - sudo mv packer /usr/bin/packer && chmod +x /usr/bin/packer

script:
  - cat /etc/ansible/ansible.cfg
  #- ansible-playbook build.playbook.yml -e build-vars.yml -i ansible_local_inventory -vv

